apiVersion: v1
kind: ConfigMap
metadata:
  name: jpuv-fluentbit
  namespace: jpuv-system
data:
  jpuv.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        HTTP_Server  On

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            docker
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name  es
        Match *
        Host  vpc-vz-jpuv-opensearch-jpuv-6pxpxpfv3y7rsysjwkmz4melwa.us-east-1.es.amazonaws.com
        Port  443
        Index jpuv-%Y.%m.%d
        Suppress_Type_Name On
        tls  On
        tls.verify Off
        HTTP_User jpuvadmin
        HTTP_Passwd Search1!

    [OUTPUT]
        Name  stdout
        Match *
